### PR TITLE
Fix(#579): Make `download_solidity_sources` work only when sources are not downloaded

### LINKED ISSUE #579: [Feature Request]: Prevent engine-tests cloning multiple times in the same target/openzeppelin-contracts directory for manual testing
### Contact Details

hyungsuk.kang@aurora.dev

### What branch had a problem?

`master`

### What happened?

`engine-tests/erc20.rs::download_solidity_sources()` function does not check whether `source_dir` exists and downloads multiple times on running the test. Due to this, `Once` instance has previously been poisoned.

To solve this, the function must check whether the openzeppelin contract files have already been cloned previous execution of test commands.

### Relevant log output

```shell
This is the log of failures due to multiple `git clone` attempts from `open-zeppelin` repo even after it was already cloned in `engine-tests/target/openzeppelin-contracts` directory

---- tests::erc20::deploy_erc_20_out_of_gas stdout ----
thread 'tests::erc20::deploy_erc_20_out_of_gas' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -4, klass: 3, message: "'target/openzeppelin-contracts' exists and is not an empty directory" }', engine-tests/src/test_utils/erc20.rs:63:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::erc20::erc20_mint stdout ----
thread 'tests::erc20::erc20_mint' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:400:21

---- tests::erc20::erc20_mint_out_of_gas stdout ----
thread 'tests::erc20::erc20_mint_out_of_gas' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:400:21

---- tests::erc20::erc20_transfer_insufficient_balance stdout ----
thread 'tests::erc20::erc20_transfer_insufficient_balance' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:400:21

---- tests::erc20::erc20_transfer_success stdout ----
thread 'tests::erc20::erc20_transfer_success' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:400:21

---- tests::erc20::profile_erc20_get_balance stdout ----
thread 'tests::erc20::profile_erc20_get_balance' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:400:21
```

### What should it be done?

The function `download_solidity_sources()` has to be replaced with code as below:

```
fn download_solidity_sources() -> PathBuf {
        let sources_dir = Path::new("target").join("openzeppelin-contracts");
        let contracts_dir = sources_dir.join("contracts");
        if contracts_dir.exists() {
            contracts_dir
        } else {
            // Contracts not already present, so download them (but only once, even
            // if multiple tests running in parallel saw `contracts_dir` does not exist).
            if !sources_dir.exists() {
                DOWNLOAD_ONCE.call_once(|| {
                    let url = "https://github.com/OpenZeppelin/openzeppelin-contracts";

                    git2::Repository::clone(url, sources_dir).unwrap();
                });
            }
            contracts_dir
        }
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hskang9**
This fixes function described in #579

### CODE REVIEW

**Review by birchmd — CHANGES_REQUESTED** [review]
https://github.com/aurora-is-near/aurora-engine/issues/579#issuecomment-1217147786

**Comment by hskang9** [comment]
Changing into feature request for manual testing

**Comment by joshuajbouw** [comment]
These need to be based off of the develop branch NOT master branch.

**Comment by birchmd** [comment]
This is not needed since #579 was caused by a different reason.

**Pull request closed without merging**
