### PR TITLE
Build(deps): Upgrade `libsecp256k1` version 0.3.5 => 0.7.0

### PR DESCRIPTION
**Pull request by RomanHodulak**
This resolves security issues with `Signature::parse` functions

See https://github.com/paritytech/libsecp256k1/commit/b525d5d318d9672a40250c1725fa1bb3156688b7

Closes https://app.clickup.com/t/2c7n5yy

### CODE REVIEW

**Comment by joshuajbouw** [comment]
Just note that this only fixes it for local precompiles, not whats currently on NEAR. Those too would need to be looked at on nearcore as we use its host function in production.

**Comment by RomanHodulak** [comment]
@joshuajbouw Ok, good to know.

Right now I'm dealing with an issue that upgrading `libsecp256k1` to `0.7.0` triggers some error that looks as if some dependency was dependent on `std` even with the `std` feature turned off.

**Comment by joshuajbouw** [comment]
yes the library is non-std, so you would need to disable it in the Cargo.toml.

**Comment by RomanHodulak** [comment]
Yes but I mean even when std is disabled

**Comment by RomanHodulak** [comment]
I'm certain that the issue is within `aurora-blake2` dependencies.

One of which is `crypto-mac`.

And that is dependent on `subtle` and that is somehow being dependent on the `std`.

Looking at the `crypto-mac` [repository](https://github.com/RustCrypto/traits), this crate has been [discontinued and superseded](https://github.com/RustCrypto/traits/pull/819) by the `digest` crate.

**Comment by joshuajbouw** [comment]
I'm updating the status to being blocked in favour of moving to std lib first. This should be done rather urgently.

See: #200

**Comment by joshuajbouw** [comment]
Needs rebasing

**Review by joshuajbouw — APPROVED** [review]

**Pull request merged**
