### PR TITLE
Bully ci

### PR DESCRIPTION
**Pull request by strokovok**
CI is fully-working right now. Key points:
1. Firstly, nearcore/aurora/bully are downloaded/prebuilt and cached, then 3 bully-pipelines (for each testnet) are starting in parallel.
2. Each bully-pipeline pulls/builds all dependencies into `.evm-bully/workdir`.
3. `mainnet-release.wasm` + `evm-bully=true` feature is used as contract for bully.
4. The current progress for each testnet is written in `.evm-bully/state.json`, whenever it becomes different from bully-result - test will fail.
5. All dependency versions (`nearcore`, `evm-bully`, `aurora-cli`) are locked in `.evm-bully/state.json` as well.
6. Bully breakpoints are published as artifacts (see _CI->Summary_ section) for each bully-CI ([example](https://github.com/aurora-is-near/aurora-engine/actions/runs/1220484247))
7. `.evm-bully/run.sh` allows to run bully-test locally

More details in [README](https://github.com/aurora-is-near/aurora-engine/tree/bully-ci/.evm-bully)

Things to work on:
- [x] Improve `cache-util` entry restoration time by implementing RW-lock instead of exclusive (inability to take exclusive cache lock leads to full nearcore rebuild, which gives us ~6min for the pipeline, but I believe that ~2.5min is achievable)
- [x] Introduce scripts for reproducing the same things on local machine (+ `replay-tx`?)
- [x] Provide more information when CI fails
- [x] [Bully-level] Fix suspicious `InvalidNonce` message in bully
- [x] Pre-build bully and aurora-engine once for all 3 testnets (will probably improve the time significantly)
- [x] Use prebuilt nearcore binary
- [x] [Bully-level] Fix `TotalPrepaidGasExceeded` issue
- [ ] [Bully-level] Skip errors that are present in original testnet

Further plans:
- [Bully-level] Avoid changing `~/.near/local`
- Introduce automatization for version-lock updates

### CODE REVIEW

**Comment by joshuajbouw** [comment]
Whats the status of this?

**Comment by strokovok** [comment]
> Whats the status of this?

WIP, need to ensure that evm-bully output actually means something useful + optimize workflow a bit

**Comment by joshuajbouw** [comment]
If tasks are not done, please change to Draft status.

**Comment by joshuajbouw** [comment]
Closing this in favour of the soon to be started "replicator" project.

**Pull request closed without merging**
