### PR TITLE
Ensure that Cargo.lock in the repo is valid

### PR DESCRIPTION
**Pull request by matklad**
At the moment, running `cargo check` locally for me:

* fails with some compilation error in the dependency
* updates Cargo.lock

That is, the Cargo.lock that is committed into the repo doesn't work. To
prevent this from happening in the future, let's forbid CI from
upgrading Cargo.lock.

### CODE REVIEW

**Comment by matklad** [comment]
This is more of an issue, rather than a pull-request -- to merge this, a working Cargo.lock needs to be supplied, and I won't be looking into fixing that.

**Review by birchmd — APPROVED** [review]
`cargo check` works for me. I'm not sure how `Cargo.lock` could have been corrupted since it is always autogenerated. That said, I don't see the harm in adding `--locked`.

**Review by joshuajbouw — APPROVED** [review]
Looks fine to me.

**Comment by artob** [comment]
@matklad @joshuajbouw Please retarget this at the `develop` branch, as per the README:
https://github.com/aurora-is-near/aurora-engine#branches

**Pull request closed without merging**
