### PR TITLE
Release 1.6.4

### PR DESCRIPTION
**Pull request by birchmd**
- `ft_metadata` bug fix (#279) 
- Spit code into separate crates for license compliance (#243) 
- Fix timestamp bug (#287)

### CODE REVIEW

**Comment by mrLSD** [comment]
@birchmd  From a source code perspective, it's can be version 1.6.4. It should be 1.7.0 - because of breaking changes in source code.

**Comment by birchmd** [comment]
As I understand it, our product is the (wasm) contract we deploy to Near and this is what the version refers to. Source code changes (even large ones like spitting into multiple crates) are not observable from the contract perspective. The only important change is the `ft_metadata` bug fix, which is why I chose 1.6.4 as the version.

**Review by joshuajbouw — APPROVED** [review]
This looks good to me. There are some small nits that I do notice such as the libs imo shouldn't be prefixed with `engine-` but, thats ok for now. Everything else and running it on my end looks good.

To be fair, we should be bumping every major version everytime we break public API. We are still technically beta, although the version says otherwise. Bumping minor in this case should be fine then.

**Review by mrLSD — APPROVED** [review]

**Review by sept-en — APPROVED** [review]

**Comment by artob** [comment]
> [O]ur product is the (wasm) contract we deploy to Near and this is what the version refers to [...]
> We should be bumping every major version every time we break public API.

Correct. We follow [semantic versioning](https://semver.org), and the versioning scheme is quite systematic and predictable.

**Pull request merged**
