### PR TITLE
replace wee_alloc to lol_alloc

### PR DESCRIPTION
**Pull request by hskang9**
## Description

This PR replaces `wee_alloc` cargo that is not currently being maintained from [dependabot](https://github.com/aurora-is-near/aurora-engine/security/dependabot/101).

## Performance / NEAR gas cost considerations

Changing allocator **increased** the near gas cost by 1~5

## Testing

All existing tests should pass on the new global allocator

## How should this be reviewed

See if there are other options on setting global allocator through `lol_alloc` for optimization on allocating memory and decreasing near gas cost.

### CODE REVIEW

**Comment by aleksuss** [comment]
As I can see, gas cost increases after replacing `wee_alloc` with `lol_alloc`. It's not good. Does it make sense to replace `wee_alloc`?

**Comment by hskang9** [comment]
I agree, `wee_alloc` is not maintained though. Maybe there will be an improvement in `lol_alloc`?

**Comment by joshuajbouw** [comment]
`wee_alloc` was deprecated and no longer maintained. To ensure highest quality, we should strive to seek better alternatives.

**Comment by aleksuss** [comment]
And one more. `wee_alloc` has more than a million downloads, and `lol_alloc` has more than one thousand.

**Comment by joshuajbouw** [comment]
Closing, as this kind of issue isn't one we are concerned about and will remain with whatever NEAR SDK uses.

**Pull request closed without merging**
