### PR TITLE
Fix dependabot issue #110

### PR DESCRIPTION
**Pull request by hskang9**
## Description

Fixes dependabot issue [110](https://github.com/aurora-is-near/aurora-engine/security/dependabot/110) and  all happening at path `/etc/xcc-router/Cargo.lock`. 

## Performance / NEAR gas cost considerations

If near gas cost changes from changing dependancies, it will appear in the CI.

## Testing

Run dependabot on this branch and issue 110 should be removed.

## How should this be reviewed

Run dependabot on this branch and issue 110 should be removed.

### CODE REVIEW

**Review by aleksuss — APPROVED** [review]

**Review by joshuajbouw — CHANGES_REQUESTED** [review]
This isn't the right way to approach this. You should never edit the Cargo.lock file directly. Whatever dependency needs to be updated, update only that dependency.

Likewise, change the title to something actually the description of the problem like `fix: <whatever the fix is>`, it doesn't have to mention Dependabot.

**Comment by aleksuss** [comment]
`cargo update` modifies `Cargo.lock` as well.

**Comment by hskang9** [comment]
Ok so after update, it still has time dependancy set to vulnerable version of `chrono` crate. Hopefully, the crate will have 0.5 soon as they just solved this security issue last week. https://github.com/chronotope/chrono/pull/969 if this happens `near_primitives` will need to be update its chrono version.

**Comment by hskang9** [comment]
Wow Near does not keep security on `chrono` package

**Review by mrLSD — APPROVED** [review]

**Comment by aleksuss** [comment]
No longer actual

**Pull request closed without merging**
