### PR TITLE
Reduce size of cargo cache in CI

### PR DESCRIPTION
**Pull request by birchmd**
Some low-hanging fruit to reduce the size of the CI cache, as suggested in https://github.com/aurora-is-near/aurora-engine/pull/92#issuecomment-843087788

### CODE REVIEW

**Comment by birchmd** [comment]
cc @matklad (couldn't tag you as a reviewer for some reason)

**Comment by matklad** [comment]
LGTM! Might be a good idea to verify locally that these env vars do what I think they should do, as cargo won't warn you if there's a typo

**Comment by birchmd** [comment]
Locally adding these environment variables reduces the size of `target` (freshly compiled after `cargo clean`) from 2.5 GB to 2.4 GB. Not a huge saving, but probably worth doing.

**Comment by matklad** [comment]
Aha, that's surprising (I'd expect something more like 3x reduction), but is explainable: 

* we disable `debug` in Cargo.toml already, so no we don't need to specifically do this for CI: https://github.com/aurora-is-near/aurora-engine/blob/master/Cargo.toml#L31
* the current rust compiled just has incremental compilation disabled https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html

So we can remove profile envs, and leave the incremental one for a bright future when incremental is back again.

**Review by artob — APPROVED** [review]

**Pull request merged**
